name: Admin UI API Check
on: [pull_request]
  #pull_request_target:
  #  types:
  #    - opened
  #    - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Check for changes to the APIs the admin UI integration uses
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: ${{ github.head_ref }}:frontend/src/schema.graphql
          fail-on-breaking: false
          annotations: true
